Some Minor UI Modifications
TechOUs/treasurejs.github.io pull request #26
Opened 2020-08-31 12:32 UTC by nitin-1926

In this PR I have fixed the following : 
1. Switch between Dark and light mode is now smooth.
2. Removed extra margins and white space between body and footer when there is no search results yet.
3. Formatted a bit of code in style.css
4. Fixed some typo errors, gave margins where felt necessary.
5. Changed the font size for the search bar heading.

2020-09-02 17:32 UTC, GauravWalia19 commented
Can you please send the PR to dev branch.

2020-09-02 17:33 UTC, GauravWalia19 requested changes
Changes looks good can you please send the same changes via PR to dev branch instead of master branch.

2020-09-03 01:44 UTC, anarchymonkey requested changes

2020-09-03 01:44 UTC, anarchymonkey commented on css/style.css
> +  color: black !important;
Please increase the specificity of this  rather than using ! important tag while doing dom interactions

2020-09-03 01:44 UTC, anarchymonkey commented on css/style.css
> +  transition: 1s;
If you are adding transition then better practice is to use ease-in/out/in-out

2020-09-03 01:44 UTC, anarchymonkey commented on css/style.css
> +  font-size: 1.25em;
If you want to use em then use in in every font-size styles otherwise revert to px.

2020-09-03 01:44 UTC, anarchymonkey commented on css/style.css
> +  text-align: center;
Can we use n-th child instead? Or first of child or last of child? With flex?

2020-09-03 01:44 UTC, anarchymonkey commented on css/style.css
> +}
Use specificity to replicate ! important tags.

2020-09-03 01:44 UTC, anarchymonkey commented on css/style.css
> +}
Use px instead of % for padding, its a bad practice.

2020-09-03 01:44 UTC, anarchymonkey commented on css/style.css
> +}
Use px instead of %

2020-09-03 01:44 UTC, anarchymonkey commented on css/style.css
> +  margin-bottom: 5%;
Use px

2020-09-03 01:44 UTC, anarchymonkey commented on css/style.css
> +  padding: 0.5%;
Use px

2020-09-03 01:44 UTC, anarchymonkey commented on css/style.css
> +}
Use px

2020-09-03 01:44 UTC, anarchymonkey commented on css/style.css
> +}
Use px

2020-09-03 01:44 UTC, anarchymonkey commented on css/style.css
> +    margin-left: 6%;
Use px

2020-09-03 01:44 UTC, anarchymonkey commented on css/style.css
> +    margin-right: 8%;
Use px

2020-09-03 01:44 UTC, anarchymonkey commented on css/style.css
> +    margin-left: 8%;
Use px

2020-09-03 01:44 UTC, anarchymonkey commented on css/style.css
> +  }
Use px

2020-09-03 01:44 UTC, anarchymonkey commented on css/style.css
> +    margin-bottom: 1%;
Use px on every margin / padding.

2020-09-03 16:07 UTC, nitin-1926 commented
@anarchymonkey I have not written the values in % or em. They were written already. I just changed the brackets indentation there to make it look clean and good. Shall I change all those values or let them be as they were?

2020-09-03 16:46 UTC, GauravWalia19 commented
@nitin-1926 can you please do the changes in the **dev** branch and here we are using **scss** so doing direct changes in css is not allowed here. For more information see the updated **CONTRIBUTING.md** file in dev branch.

2020-09-03 16:47 UTC, GauravWalia19 requested changes
@nitin-1926 can you please do the changes in the **dev** branch and here we are using scss so doing direct changes in css is not allowed here. For more information see the updated **CONTRIBUTING.md file** in **dev** branch.

2020-09-05 10:15 UTC, nitin-1926 commented
@GauravWalia19  Sure, shall I close this PR and open a PR for DEV branch right away?

2020-09-05 11:41 UTC, anarchymonkey commented
Just repoint to dev maybe?

On Sat, Sep 5, 2020, 3:45 PM Nitin Gupta <notifications@github.com> wrote:

> @GauravWalia19 <https://github.com/GauravWalia19> Sure, shall I close
> this PR and open a PR for DEV branch right away?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/TechOUs/treasurejs.github.io/pull/26#issuecomment-687584720>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHP2D2R27JAIB6FVBHH4YW3SEIFTJANCNFSM4QQO4JVQ>
> .
>

2020-09-05 15:37 UTC, GauravWalia19 commented
@anarchymonkey I think closing the PR and creating new will be right thing because this PR has problems so I am closing this now @nitin-1926. Send new PR @nitin-1926.

2020-09-05 15:37 UTC, closed without merging